[package]
name = "cargo-atcoder"
version = "0.2.0"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Cargo subcommand for AtCoder"
repository = "https://github.com/tanakh/cargo-atcoder"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["cli", "procon"]

[dependencies]
anyhow = "1.0.28"
bytesize = "1.0.0"
cargo_metadata = "0.9.1"
chrono = "0.4.11"
console = "0.11.2"
cookie_0_12_0 = { package = "cookie", version = "=0.12.0" }
cookie_store = "0.11.0"
data-encoding = "2.2.0"
dialoguer = "0.6.2"
dirs = "2.0.2"
futures = "0.3.4"
if_chain = "1.0.0"
indicatif = "0.14.0"
itertools = "0.9.0"
lazy_static = "1.4.0"
notify = "4.0.15"
regex = "1.3.7"
scraper = "0.12.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
sha2 = "0.8.1"
structopt = "0.3.14"
thiserror = "1.0.16"
tokio = { version = "0.2.20", features = ["blocking", "rt-core", "macros", "time"] }
toml = "0.5.6"
toml_edit = "0.1.5"
unicode-width = "0.1.7"
ureq_1_0_0 = { package = "ureq", version = "=1.0.0", default-features = false, features = ["tls"] }
url = "2.1.1"
which = "3.1.1"
