[package]
name = "cargo-atcoder"
version = "0.1.0"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.5"
dirs = "2.0"
reqwest = { version = "0.10", features = ["cookies"] }
scraper = "0.11"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros"] }
toml = "0.5"
