[package]
name = "cargo-atcoder"
version = "0.1.0"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytesize = "1.0"
chrono = "0.4"
console = "0.9"
data-encoding = "2.1"
dialoguer = "0.5"
dirs = "2.0"
futures = "0.3"
handlebars = "2.0"
if_chain = "1"
indicatif = "0.13"
itertools = "0.8"
lazy_static = "1.4.0"
notify = "4.0"
regex = "1"
reqwest = { git = "https://github.com/tanakh/reqwest.git", branch = "expose_cookie", features = ["cookies"] }
scraper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros", "time"] }
toml = "0.5"
which = "3.1"
