[package]
name = "cargo-atcoder"
version = "0.1.0"
authors = ["Hideyuki Tanaka <tanaka.hideyuki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
cargo_toml = "0.8"
console = "0.9"
dialoguer = "0.5"
dirs = "2.0"
futures = "0.3"
notify = "4.0"
reqwest = { path = "reqwest", features = ["cookies"] }
scraper = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.8"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros", "time"] }
toml = "0.5"
tui = "0.8"
termion = "1.5"
