[profile]
target = "x86_64-unknown-linux-musl"

[profile.release]
lto = true
panic = 'abort'

[dependencies]

[project]
# rustc_version = "1.15.1"

template = """
fn main() {
    unimplemented!();
}
"""
