name: Rust

on: [push, pull_request]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup `stable-x86_64-unknown-linux-gnu`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        default: true
        profile: minimal
        components: rustfmt

    - name: Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
        - stable-x86_64-apple-darwin
        - stable-x86_64-unknown-linux-gnu
        include:
        - { toolchain: stable-x86_64-apple-darwin     , os: macos-10.15  }
        - { toolchain: stable-x86_64-unknown-linux-gnu, os: ubuntu-18.04 }

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup `${{ matrix.toolchain }}`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        default: true
        profile: minimal
        components: clippy

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
